### ISSUE TITLE
Error: Process completed with exit code 28.

### ISSUE THREAD

**Issue by GuihongWang** [fscarmen/warp-on-actions#1]
WARP mode: wireguard.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3631 B]
Get:7 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1325 kB]
Get:8 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [267 kB]
Get:9 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1342 kB]
Get:10 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [220 kB]
Get:11 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1036 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [232 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [42.1 kB]
Hit:14 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1109 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [207 kB]
Get:17 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1313 kB]
Get:18 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [214 kB]
Get:19 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [835 kB]
Get:20 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [159 kB]
Get:21 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [33.0 kB]
Get:22 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [124 kB]
Get:23 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [11.0 kB]
Fetched 8703 kB in 1s (6831 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
iproute2 is already the newest version (5.15.0-1ubuntu2).
net-tools is already the newest version (1.60+git20181103.0eebece-1ubuntu5).
iptables is already the newest version (1.8.7-1ubuntu5.1).
iptables set to manually installed.
dnsutils is already the newest version (1:9.18.18-0ubuntu0.22.04.1).
The following NEW packages will be installed:
  openresolv wireguard-tools
0 upgraded, 2 newly installed, 0 to remove and 40 not upgraded.
Need to get 113 kB of archives.
After this operation, 433 kB of additional disk space will be used.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:2 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 openresolv all 3.12.0-2 [25.6 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 wireguard-tools amd64 1.0.20210914-1ubuntu2 [86.9 kB]
Fetched 113 kB in 0s (1545 kB/s)
Selecting previously unselected package openresolv.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 276954 files and directories currently installed.)
Preparing to unpack .../openresolv_3.12.0-2_all.deb ...
Unpacking openresolv (3.12.0-2) ...
Selecting previously unselected package wireguard-tools.
Preparing to unpack .../wireguard-tools_1.0.20210914-1ubuntu2_amd64.deb ...
Unpacking wireguard-tools (1.0.20210914-1ubuntu2) ...
Setting up wireguard-tools (1.0.20210914-1ubuntu2) ...
wg-quick.target is a disabled or a static unit not running, not starting it.
Setting up openresolv (3.12.0-2) ...
Processing triggers for man-db (2.10.2-1) ...
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 6.2.0-1018-azure
NEEDRESTART-KEXP: 6.2.0-1018-azure
NEEDRESTART-KSTA: 1
[Interface]
PrivateKey = cKE7LmCF61IhqqABGhvJ44jWXp8fKymcMAEVAzbDF2k=
Address = 172.16.0.2/32
Address = fd01:5ca1:ab1e:823e:e094:eb1c:ff87:1fab/128
PostUp = ip -4 rule add from 10.1.0.70 lookup main
PostDown = ip -4 rule delete from 10.1.0.70 lookup main
DNS = 8.8.8.8,8.8.4.4
MTU = 1280
[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0
AllowedIPs = ::/0
Endpoint = 162.159.193.10:2408
[#] ip link add warp type wireguard
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add fd01:5ca1:ab1e:823e:e094:eb1c:ff87:1fab/128 dev warp
[#] ip link set mtu 1280 up dev warp
[#] resolvconf -a warp -m 0 -x
[#] wg set warp fwmark 51820
[#] ip -6 route add ::/0 dev warp table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] nft -f /dev/fd/63
[#] ip -4 route add 0.0.0.0/0 dev warp table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] nft -f /dev/fd/63
[#] ip -4 rule add from 10.1.0.70 lookup main
Error: Process completed with exit code 28.

**Comment by fscarmen** [comment]
以下是我的测试，2个方式都是可以的，具体日志如下，可以看到 wireguard 会远远比 client 快，但因为是使用 wireguard 内核接入，在美国某些地方如LA可能获取不了 warp IP。你先多试两次，如果用户反馈多接入不了，我考虑加入带 reserved 功能 wireguard-go。

https://github.com/fscarmen/warp-on-actions/actions/runs/7650662832

<img width="940" alt="image" src="https://github.com/fscarmen/warp-on-actions/assets/62703343/da7f880d-561d-41e4-9c98-699ecbd5de89">

```
Run fscarmen/warp-on-actions@v1.0
Run if [ "wireguard" == 'client' ]; then
WARP mode: wireguard.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [1[4](https://github.com/fscarmen/warp-on-actions/actions/runs/7650662832/job/20998765303#step:2:5)2 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3631 B]
Get:7 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1325 kB]
Get:8 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [267 kB]
Get:9 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1342 kB]
Get:10 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [220 kB]
Get:11 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1036 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [232 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [42.1 kB]
Hit:14 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1109 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [207 kB]
Get:17 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1313 kB]
Get:18 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [214 kB]
Get:19 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [835 kB]
Get:20 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [159 kB]
Get:21 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [33.0 kB]
Get:22 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [11.0 kB]
Get:23 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [124 kB]
Fetched 8703 kB in 1s (6776 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
iproute2 is already the newest version (5.15.0-1ubuntu2).
net-tools is already the newest version (1.60+git20181103.0eebece-1ubuntu5).
iptables is already the newest version (1.8.7-1ubuntu5.1).
iptables set to manually installed.
dnsutils is already the newest version (1:9.18.18-0ubuntu0.22.04.1).
The following NEW packages will be installed:
  openresolv wireguard-tools
0 upgraded, 2 newly installed, 0 to remove and 40 not upgraded.
Need to get 113 kB of archives.
After this operation, 433 kB of additional disk space will be used.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:2 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 openresolv all 3.12.0-2 [25.6 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 wireguard-tools amd64 1.0.20210914-1ubuntu2 [86.9 kB]
Fetched 113 kB in 0s (850 kB/s)
Selecting previously unselected package openresolv.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... [45](https://github.com/fscarmen/warp-on-actions/actions/runs/7650662832/job/20998765303#step:2:47)%
(Reading database ... [50](https://github.com/fscarmen/warp-on-actions/actions/runs/7650662832/job/20998765303#step:2:52)%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 276954 files and directories currently installed.)
Preparing to unpack .../openresolv_3.12.0-2_all.deb ...
Unpacking openresolv (3.12.0-2) ...
Selecting previously unselected package wireguard-tools.
Preparing to unpack .../wireguard-tools_1.0.20210914-1ubuntu2_amd64.deb ...
Unpacking wireguard-tools (1.0.20210914-1ubuntu2) ...
Setting up wireguard-tools (1.0.20210914-1ubuntu2) ...
wg-quick.target is a disabled or a static unit not running, not starting it.
Setting up openresolv (3.12.0-2) ...
Processing triggers for man-db (2.10.2-1) ...
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 6.2.0-1018-azure
NEEDRESTART-KEXP: 6.2.0-1018-azure
NEEDRESTART-KSTA: 1
[Interface]
PrivateKey = cKE7LmCF61IhqqABGhvJ44jWXp8fKymcMAEVAzbDF2k=
Address = 172.16.0.2/32
Address = fd01:5ca1:ab1e:823e:e094:eb1c:ff87:1fab/128
PostUp = ip -4 rule add from 10.1.0.253 lookup main
PostDown = ip -4 rule delete from 10.1.0.253 lookup main
DNS = 8.8.8.8,8.8.4.4
MTU = 1280

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo[51](https://github.com/fscarmen/warp-on-actions/actions/runs/7650662832/job/20998765303#step:2:53)h2wPfgyo=
AllowedIPs = 0.0.0.0/0
AllowedIPs = ::/0
Endpoint = 162.159.193.10:2408
[#] ip link add warp type wireguard
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add fd01:5ca1:ab1e:823e:e094:eb1c:ff87:1fab/128 dev warp
[#] ip link set mtu 1280 up dev warp
[#] resolvconf -a warp -m 0 -x
[#] wg set warp fwmark 51820
[#] ip -6 route add ::/0 dev warp table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] nft -f /dev/fd/63
[#] ip -4 route add 0.0.0.0/0 dev warp table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] nft -f /dev/fd/63
[#] ip -4 rule add from 10.1.0.2 lookup main
{"organization":"Cloudflare Warp","longitude":-87.6318,"city":"Chicago","timezone":"America\/Chicago","isp":"Cloudflare Warp","offset":-21[60](https://github.com/fscarmen/warp-on-actions/actions/runs/7650662832/job/20998765303#step:2:62)0,"region":"Illinois","asn":13335,"asn_organization":"CLOUDFLARENET","country":"United States","ip":"104.28.195.105","latitude":41.88[74](https://github.com/fscarmen/warp-on-actions/actions/runs/7650662832/job/20998765303#step:2:76),"postal_code":"60602","continent_code":"NA","country_code":"US","region_code":"IL"}
```

**Comment by NyaMisty** [comment]
wireguard 快没用吧，Github Actions这种场景稳定性才是第一位
顺便，如果不想要warp的v4可以加上
sudo warp-cli --accept-tos add-excluded-route 0.0.0.0/0

**Comment by GuihongWang** [comment]
> wireguard 快没用吧，Github Actions这种场景稳定性才是第一位
> 顺便，如果不想要warp的v4可以加上
> sudo warp-cli --accept-tos add-excluded-route 0.0.0.0/0

wireguard有完整隐藏ip

**Comment by fscarmen** [comment]
> wireguard 快没用吧，Github Actions这种场景稳定性才是第一位 顺便，如果不想要warp的v4可以加上 sudo warp-cli --accept-tos add-excluded-route 0.0.0.0/0

话说日后可以添加 ipv4 / ipv6 和 双栈选项进去，原来弄这个是为了 freenom 续期 ac，官网禁止了 github 的 IP，使用 warp 能解决而弄的，所以没有动力更新了。

**Comment by NyaMisty** [comment]
> > wireguard 快没用吧，Github Actions这种场景稳定性才是第一位 顺便，如果不想要warp的v4可以加上 sudo warp-cli --accept-tos add-excluded-route 0.0.0.0/0
> 
> 话说日后可以添加 ipv4 / ipv6 和 双栈选项进去，原来弄这个是为了 freenom 续期 ac，官网禁止了 github 的 IP，使用 warp 能解决而弄的，所以没有动力更新了。

我自己随便改了一个，已经丢上去用了哈哈

**Comment by fscarmen** [comment]
v1.1
* Support WARP ipv4 , ipv6 and dualstack.
* Remove wireguard mode because it is unstable.

<img width="1558" alt="image" src="https://github.com/fscarmen/warp-on-actions/assets/62703343/d4fecbcb-ce31-43f5-b8a7-350571cee92d">

**Comment by GuihongWang** [comment]
```

Warning: The "register" command will be deprecated in a future release. Please use "registration new" instead

Success
Warning: The "set-mode" command will be deprecated in a future release. Please use "mode" instead

Success
Success
Error: Process completed with exit code 6.
```
不知道为什么会出现错误6  &instead

**Comment by fscarmen** [comment]
> ```
> 
> Warning: The "register" command will be deprecated in a future release. Please use "registration new" instead
> 
> Success
> Warning: The "set-mode" command will be deprecated in a future release. Please use "mode" instead
> 
> Success
> Success
> Error: Process completed with exit code 6.
> ```
> 
> 不知道为什么会出现错误6 &instead

instead 可以不用理会的， error 6 就不清楚了，我在 ac 里跑了一下是正常的，你多试一下。

<img width="1543" alt="image" src="https://github.com/user-attachments/assets/a0e23c5c-1a14-4e02-961f-7d2dac2e2163">

**Comment by fscarmen** [comment]
> ```
> 
> Warning: The "register" command will be deprecated in a future release. Please use "registration new" instead
> 
> Success
> Warning: The "set-mode" command will be deprecated in a future release. Please use "mode" instead
> 
> Success
> Success
> Error: Process completed with exit code 6.
> ```
> 
> 不知道为什么会出现错误6 &instead

我怀疑是你的版本出问题，我半年前已经换了新指令的了，你看项目说明的写
